[palettes.matugen]
color_1 = '{{colors.primary.default.hex}}'
color_2 = '{{colors.secondary.default.hex}}'
color_3 = '{{colors.tertiary.default.hex}}'
color_4 = '{{colors.primary_container.default.hex}}'
color_5 = '{{colors.secondary_container.default.hex}}'
color_6 = '{{colors.tertiary_container.default.hex}}'
color_bg = '{{colors.surface.default.hex}}'
color_fg = '{{colors.on_surface.default.hex}}'
color_text_dark = '{{colors.on_primary.default.hex}}'
color_text_light = '{{colors.on_primary_container.default.hex}}'
color_error = '{{colors.error.default.hex}}'
color_success = '{{colors.primary.default.hex}}'